PAIR_SYMBOLS = ["BTCUSDT","ETHUSDT","LTCUSDT","XRPUSDT","BNBUSDT","ADAUSDT","DOTUSDT","LINKUSDT","BCHUSDT","DASHUSDT"]
BALANCE_SYMBOLS = ["USDT","LTC"]

TIME_LENGTH = 32
IMG_LENGTH = 128
CHECKPOINT_PATH = "TrainData/checkpoint.ckpt"


